version: '3.7'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8082:8082"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"